#%RAML 1.0 ResourceType
usage: Use this resourceType to represent a collection of assets
description: A collection of assets
is: [assetsPagination, assets-search]
get:
  description: Gets a paginated set of assets
  responses:
    200:
      body:
        application/json:
          type: BasicAsset[]
          example: !include ../examples/assets.json
