#%RAML 1.0 ResourceType
description: Asset mutable data resource type
patch:
  description: Patch an asset mutable data
  headers:
      Content-Type:
        description: Use "multipart/form-data"
        type: string
        example: multipart/form-data
        required: true
  body:
    multipart/form-data:
      properties:
        tags:
          description: |
            A comma-separed string values that represents the asset's tags.
          type: string
          required: false
          example: tag1, tag2
        fields:
          description: |
            A comma-separed string values that represents the asset's custom fields.
            The field's name should have the following format: fields.customFieldKey. Example: "fields.Maintainer"
          type: string
          required: false
          example: 'Mulesoft, Exchange'
        categories:
          description: |
            A comma-separed string values that represents the asset's categories.
            The field's name should have the following format: fields.categoryKey. Example: "categories.sector"
          type: string
          required: false
          example: 'Finance, IT'
        files.docs.zip:
          description: A zip file containing portal documentation
          required: false
          type: file
  responses:
    202:
      description: Asset asynchronous mutable data publication has been started, the link provided in the body will have the necessary information to know its status
      body:
        application/json:
          example: !include ../examples/v2/mutable-data-accepted.json
