#%RAML 1.0 ResourceType

usage: Use this resourceType to represent a collection of an asset review comments
description: A collection of asset review comments
post:
    description: Creates a new review comment.
    body:
        application/json:
            schema:  !include ../schemas/post-review-comment-body.json
            example: !include ../examples/post-review-comment-body.json
    responses:
        201:
            body:
                application/json:
                    example: !include ../examples/review-comment.json
