#%RAML 1.0 ResourceType

usage: Use this resourceType to represent the comment of an asset review
description: A single asset review comment
patch:
    description: Edits a comment
    body:
        application/json:
            schema:  !include ../schemas/patch-review-comment-body.json
            example: !include ../examples/patch-review-comment-body.json
    responses:
        200:
            body:
                application/json:
                    example: !include ../examples/review-comment.json
delete:
    description: Deletes an specific asset review comment.
    responses:
        204:
            description: comment deleted
