#%RAML 1.0 ResourceType
usage: Use this resourceType to represent an asset with includeSnapshot query parameter
description: An asset
get:
  description: Gets an asset
  queryParameters:
    includeSnapshots?:
      displayName: Include snapshots
      example: true
      description: Include snapshots in the results
      type: boolean
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/asset.json
