#%RAML 1.0 ResourceType
usage: Use this resourceType to represent a cookieConsentId
get:
  description: Gets cookie consent id
  responses:
    200:
      body:
        text/plain:
          example: 88520c5c-fa3c-4381-85bb-8Ccdb9b543974
