#%RAML 1.0 ResourceType

usage: Use this resourceType to represent a collection of files
description: A collection of files
get:
  description: Gets asset files
  displayName: Asset files
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/v2/get-files.json
