#%RAML 1.0 ResourceType

usage: Use this resourceType to represent a collection of minor versions
description: A collection of minor versions
get:
  description: Gets asset minor versions
  displayName: Asset minor versions
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/v2/get-minor-versions.json
