#%RAML 1.0 Trait

headers:
  x-resources-count:
    type: number
    description: The total amount of envi affected by the policy, where the user has permissions to see them, pagination purpose.
  x-total-count:
    type: number
    description: The total amount of envi affected by the policy even if the user has no permissions to see them.
