queryParameters:
  includeSnapshots:
    displayName: includeSnapshots
    type: boolean
    description: Filters results depending on whether the snapshots is enabled or not
    required: false
    repeat: false
