queryParameters:
  search:
    displayName: Search
    type: string
    required: false
    description: Search parameter used to filter facets
    example: "my name"
responses:
  200:
    body:
      application/json:
        example: !include ../examples/facets.json
