#%RAML 1.0
title: exchange-xapi
version: 2.0
mediaType: application/json
description: v2 private routes
baseUri: https://anypoint.mulesoft.com/exchange/api/v2

traits:
  assets-search: !include traits/assets-search.raml
  pagination: !include traits/paginationv2.raml
  assetsPagination: !include traits/assetsPagination.raml
  facets: !include traits/facets.raml
  angSearchable: !include traits/angSearchable.raml

types:
  BasicAsset: !include types/basicAsset.raml

resourceTypes:
  asset: !include resourceTypes/asset.raml

  assets: !include resourceTypes/assets.raml

  completeAsset: !include resourceTypes/completeAsset.raml

  files: !include resourceTypes/files.raml

  minorVersions: !include resourceTypes/minorVersions.raml

  versionGroups: !include resourceTypes/versionGroups.raml


/ping:
  description: API Status
  displayName: Ping
  get:
    description: Checks API status
    responses:
      200:
        body:
          application/json:
            example: !include examples/ping-response.json

/health:
  description: API Health
  displayName: Health
  get:
    description: Checks API status of services that are used by this API
    responses:
      200:
        body:
          application/json:
            example: !include examples/health-response.json

/profile:
  displayName: Profile
  description: User profile
  get:
    description: Gets user profile
    responses:
      200:
        body:
          application/json:
            example: !include examples/profile.json

/organizations:
  /{organizationId}:
    uriParameters:
      organizationId:
        description: The Id of organization
        type: string
        pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
        example: "434b78c3-bcd9-412d-9428-dec2f8c72cb2"

    /assets/{groupId}/{assetId}:
      description: Assets by group and asset id
      displayName: Group Asset

      /{version}:
        description: Asset version
        displayName: Version
        uriParameters:
          version:
            description: Asset version
            type: string
            pattern: ^v{0,1}(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
            example: "2.22.45"

        /owner:
          description: Asset ownership
          displayName: Owner
          put:
            description: Updates Asset ownership
            body:
              application/json:
                type: !include schemas/assetOwner.json
                example: !include examples/assetOwner.json
            responses:
              204:
                description: Asset ownership successfully updated

  /{organizationDomain}:
    displayName: Organizations by Domain
    description: Organizations by domain
    uriParameters:
      organizationDomain:
        description: Domain of a master organization
        type: string
        maxLength: 255
        example: some-domain

    /assets:
      displayName: Assets
      description: Assets
      type: assets

  /groups:
    description: Organization groups
    displayName: Groups
    get:
      description: Gets eligible groupId's for given organizationId
      responses:
        200:
          body:
            application/json:
              example: !include examples/organization-groups.json

  /facets:
    displayName: Facets
    description: Organization facets
    get:
      description: Retrieves facets for the organization
      is: [facets]

  /ang/facets:
    displayName: Facets
    description: Organization facets for ANG types
    get:
      description: Retrieves facets for the organization
      is: [facets]

  /ang/facets/{facetName}:
    displayName: Facet by name
    description: Organization facet for ANG by name
    get:
      description: Retrieves facets for the organization
      is: [facets]

/files/classifiers/{classifier}/entries/main:
    displayName: Main Files
    description: Main Files
    post:
      description: Gets package's main files from the given zip file
      headers:
        Content-Type:
          type: string
          required: true
          description: It may be 'multipart/form-data', 'application/octet-stream', etc.
      body:
        "application/zip":
      responses:
        200:
          body:
            application/json:
              example: !include examples/mainFilesResponse.json

/assets:
  displayName: Assets
  description: Assets
  type: assets

  /{groupId}/{assetId}:
    displayName: Asset
    description: Asset
    type: completeAsset
    uriParameters:
      groupId:
        description: groupId of the asset
        type: string
      assetId:
        description: assetId of the asset
        type: string

    /dependencies:
      description: Gets all asset versions with their dependencies
      displayName: Dependencies
      get:
        responses:
          200:
            body:
              application/json:
                example: !include examples/v2/get-versions-dependencies.json

    /dependents:
      description: Dependents
      post:
        description: |
          Returns the dependents for all versions specified in request body
          - For some assets versionGroup can equal version
        body:
          application/json:
            example: !include examples/v2/get-versions-dependents.json
            type: !include schemas/v2/get-versions-dependents.json
        responses:
          200:
            description: Dependent assets
            body:
              application/json:
                example: !include examples/v2/get-versions-dependents-response.json

    /files:
      displayName: Files
      description: Files for a given asset
      type: files

    /minorVersions:
      description: Asset minor versions
      displayName: Asset minor versions
      type: minorVersions

      /{minorVersion}:
        description: Assets by minor version
        displayName: Assets by minor version
        type: asset
        uriParameters:
          minorVersion:
            type: string
            description: Minor version
            pattern: ^[0-9]+\.[0-9]+$
            example: "2.22"

    /versionGroups:
      /{versionGroup}:
        description: Asset by version group
        displayName: Asset by version group
        type: asset
        uriParameters:
          versionGroup:
            description: Version group of the asset
            type: string

    /{version}:
      displayName: Asset Version
      description: Asset version
      type: completeAsset
      uriParameters:
        version:
          description: version of the asset
          type: string
          pattern: ^v{0,1}(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
          example: "2.22.45"

      /api:
        displayName: API
        description: API

        /query/platformSupport:
          displayName: Support
          description: Support
          get:
            description: Get platform support for specified asset
            responses:
              200:
                description: Returns platform for this asset

      /icon:
        description: Asset icon
        displayName: Icon
        put:
          description: |
            Uploads an icon as a binary file.
            - Body should be application/json. This is not specified in the raml as it conflicts with Osprey.
          body:
            "*/*":
              example: !include ./examples/v2/icon.svg
          responses:
            204:
              description: Icon has been uploaded
            400:
              description: Invalid icon
            404:
              description: Asset does not exist

      /reviews/search:
        displayName: Reviews
        description: Reviews
        post:
          displayName: Gets version reviews
          description: Given an array of versions, this endpoint retrieves the reviews for the specified versions
          body:
            application/json:
              type: !include schemas/post-search-versions-reviews-body.json
              example: !include examples/post-search-versions-reviews-result-body.json
          responses:
            200:
              body:
                application/json:
                  example: !include ./examples/reviews.json

/portals:
  displayName: Public portals
  description: Public portals

  /{organizationDomain}:
    displayName: Portal domain
    description: Public portal domain

    /assets:
      displayName: Public assets
      description: Public assets
      type: assets

      /{groupId}/{assetId}:
        displayName: Asset
        description: Public asset by groupId and assetId
        type: asset

        /versionGroups:
          displayName: Version groups
          description: Retrieve public version groups of an asset
          type: versionGroups

          /{versionGroup}:
            displayName: By versionGroup
            description: Public asset by versionGroup
            type: asset
            uriParameters:
              versionGroup:
                description: Version group of the asset
                type: string

        /minorVersions:
          displayName: Minor versions
          description: Asset minor versions
          type: minorVersions

          /{minorVersion}:
            displayName: By minor version
            description: Public asset by minor version
            type: asset
            uriParameters:
              minorVersion:
                type: string
                description: Minor version
                pattern: ^[0-9]+\.[0-9]+$
                example: "2.22"

        /{version}:
          displayName: Asset Version
          description: Public asset version
          type: asset
          uriParameters:
            version:
              description: version of the asset
              type: string
              pattern: ^v{0,1}(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
              example: "2.22.45"

/facets:
  displayName: Facets
  description: User facets
  get:
    description: Retrieves facets for the user
    is: [facets]

/ang:
  displayName: ANG
  description: ANG

  /facets:
    displayName: Facets
    description: User facets using ANG types
    get:
      description: Retrieves facets for the user
      is: [facets]

  /jobs:
    displayName: Jobs
    description: Jobs to populate data in ANG
    post:
      description: |
        Sets jobs to populate data of some master organizations in ANG.
        - Body should be application/json. This is not specified in the raml as it conflicts with Osprey.
      body:
        "*/*":
          example: !include ./examples/v2/angOrganizationJobs.json

    /assets/{groupId}/{assetId}:
      post:
        description: Posts (asynchronously) an existing asset in asset manager to ANG Service
        responses:
          204:
            description: Post was queued up to be processed
  /assets/{groupId}/{assetId}/node:
    get:
      description: Get ang Asset node
      responses:
        200:
          body:
            application/yaml:
              example: !include examples/v2/catalogAngAsset.yaml

  /organizations/stats:
    displayName: Organization Stats
    description: Stats from organizations non migrated in ANG
    get:
      description: Gets a list of stats of non migrated organizations to ANG
      responses:
        200:
          body:
            application/json:
              example: !include ./examples/v2/angOrganizationStats.json

  /_search:
    displayName: Search
    description: ANG Search
    get:
      description: Makes an asset search using ANG Service with a GET to asset-minor-versions-view/_search endpoint (forwarding the unmodified queryString)
      is: [ angSearchable ]

  /stream/_search:
    displayName: Stream Search
    description: ANG Search that accepts JSON streaming
    get:
      description: Makes an asset search using ANG Service with a GET to /_search endpoint that accepts JSON streaming
      is: [ angSearchable ]

/debug/query:
  post:
    description: Forwards a read only named query in Asset Manager for debug purposes

/migrations:
  post:
    description: Executes a migration previously defined in asset-manager asynchronously, returns the number of rows affected.
